-- 회원
CREATE TABLE `MEMBER` (
	`MEMIDX`    INTEGER     NOT NULL COMMENT '회원번호', -- 회원번호
	`MEMEMAIL`  VARCHAR(40) NOT NULL COMMENT '이메일', -- 이메일
	`MEMPW`     VARCHAR(30) NOT NULL COMMENT '비밀번호', -- 비밀번호
	`MEMNAME`   VARCHAR(50) NOT NULL COMMENT '이름', -- 이름
	`MEMNICK`   VARCHAR(50) NOT NULL COMMENT '닉네임', -- 닉네임
	`MEMPHONE`  INTEGER     NOT NULL COMMENT '핸드폰번호', -- 핸드폰번호
	`MEMBIRTH`  INTEGER     NOT NULL COMMENT '생년월일', -- 생년월일
	`MEMGENDER` VARCHAR(5)  NOT NULL COMMENT '성별', -- 성별
	`MEMPHOTO`  MEDIUMBLOB  NULL     COMMENT '회원사진' -- 회원사진
)
COMMENT '회원';

-- 회원
ALTER TABLE `MEMBER`
	ADD CONSTRAINT `PK_MEMBER` -- 회원 기본키
		PRIMARY KEY (
			`MEMIDX` -- 회원번호
		);

ALTER TABLE `MEMBER`
	MODIFY COLUMN `MEMIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '회원번호';

ALTER TABLE `MEMBER`
	AUTO_INCREMENT = 1;

-- 게시판
CREATE TABLE `BOARD` (
	`POSTIDX`       INTEGER      NOT NULL COMMENT '게시글IDX', -- 게시글IDX
	`POSTNAME`      VARCHAR(255) NOT NULL COMMENT '제목', -- 제목
	`POSTCONTENT`   MEDIUMTEXT   NOT NULL COMMENT '글내용', -- 글내용
	`POSTNICK`      VARCHAR(50)  NOT NULL COMMENT '닉네임', -- 닉네임
	`MEMIDX`        INTEGER      NOT NULL COMMENT '회원번호', -- 회원번호
	`UPLOADFILE`    MEDIUMBLOB   NULL     COMMENT '첨부파일', -- 첨부파일
	`POSTDATE`      TIMESTAMP    NOT NULL COMMENT '작성일자', -- 작성일자
	`POSTVIEW`      INTEGER      NOT NULL COMMENT '조회수', -- 조회수
	`POSTLIKE`      INTEGER      NULL     COMMENT '좋아요갯수', -- 좋아요갯수
	`BOARDCATEGORY` VARCHAR(50)  NOT NULL COMMENT '말머리' -- 말머리
)
COMMENT '게시판';

-- 게시판
ALTER TABLE `BOARD`
	ADD CONSTRAINT `PK_BOARD` -- 게시판 기본키
		PRIMARY KEY (
			`POSTIDX` -- 게시글IDX
		);

ALTER TABLE `BOARD`
	MODIFY COLUMN `POSTIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '게시글IDX';

ALTER TABLE `BOARD`
	AUTO_INCREMENT = 1;

-- 채팅방내용
CREATE TABLE `CHATROOM` (
	`MESSAGEIDX`  INTEGER    NOT NULL COMMENT '메세지 번호', -- 메세지 번호
	`CHATIDX`     INTEGER    NOT NULL COMMENT '채팅방번호', -- 채팅방번호
	`CHATCONTENT` MEDIUMTEXT NOT NULL COMMENT '대화내용', -- 대화내용
	`CHATDATE`    TIMESTAMP  NOT NULL COMMENT '대화시간', -- 대화시간
	`CRIDX`       INTEGER    NOT NULL COMMENT '캐리번호', -- 캐리번호
	`MEMIDX`      INTEGER    NOT NULL COMMENT '회원번호' -- 회원번호
)
COMMENT '채팅방내용';

-- 채팅방내용
ALTER TABLE `CHATROOM`
	ADD CONSTRAINT `PK_CHATROOM` -- 채팅방내용 기본키
		PRIMARY KEY (
			`MESSAGEIDX` -- 메세지 번호
		);

ALTER TABLE `CHATROOM`
	MODIFY COLUMN `MESSAGEIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '메세지 번호';

ALTER TABLE `CHATROOM`
	AUTO_INCREMENT = 1;

-- 회원바디기록
CREATE TABLE `MEMBERBODYINFO` (
	`MEMO`    MEDIUMTEXT NULL     COMMENT '타입', -- 타입
	`MEMDATE` TIMESTAMP  NULL     COMMENT '날짜', -- 날짜
	`MEMIDX`  INTEGER    NOT NULL COMMENT '회원번호' -- 회원번호
)
COMMENT '회원바디기록';

-- 게시판댓글
CREATE TABLE `BOARDCOMMENT` (
	`COMMENTIDX`     INTEGER     NOT NULL COMMENT '댓글IDX', -- 댓글IDX
	`POSTIDX`        INTEGER     NOT NULL COMMENT '게시글IDX', -- 게시글IDX
	`COMMENTNICK`    VARCHAR(50) NOT NULL COMMENT '닉네임', -- 닉네임
	`COMMENTCONTENT` MEDIUMTEXT  NOT NULL COMMENT '댓글내용', -- 댓글내용
	`COMMENTDATE`    TIMESTAMP   NOT NULL COMMENT '댓글작성일자' -- 댓글작성일자
)
COMMENT '게시판댓글';

-- 게시판댓글
ALTER TABLE `BOARDCOMMENT`
	ADD CONSTRAINT `PK_BOARDCOMMENT` -- 게시판댓글 기본키
		PRIMARY KEY (
			`COMMENTIDX` -- 댓글IDX
		);

ALTER TABLE `BOARDCOMMENT`
	MODIFY COLUMN `COMMENTIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '댓글IDX';

ALTER TABLE `BOARDCOMMENT`
	AUTO_INCREMENT = 1;

-- 결제
CREATE TABLE `PAYMENT` (
	`PAYIDX`   INTEGER   NOT NULL COMMENT '결제번호', -- 결제번호
	`PAYPRICE` INTEGER   NOT NULL COMMENT '결제금액', -- 결제금액
	`PAYDATE`  TIMESTAMP NOT NULL COMMENT '결제날짜', -- 결제날짜
	`PRONUM`   INTEGER   NOT NULL COMMENT '수업횟수', -- 수업횟수
	`MEMIDX`   INTEGER   NOT NULL COMMENT '회원번호', -- 회원번호
	`PROIDX`   INTEGER   NOT NULL COMMENT '수업IDX' -- 수업IDX
)
COMMENT '결제';

-- 결제
ALTER TABLE `PAYMENT`
	ADD CONSTRAINT `PK_PAYMENT` -- 결제 기본키
		PRIMARY KEY (
			`PAYIDX` -- 결제번호
		);

ALTER TABLE `PAYMENT`
	MODIFY COLUMN `PAYIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '결제번호';

ALTER TABLE `PAYMENT`
	AUTO_INCREMENT = 1;

-- 캐리정보
CREATE TABLE `CARRY` (
	`CRIDX`     INTEGER      NOT NULL COMMENT '캐리IDX', -- 캐리IDX
	`CRID`      INTEGER      NOT NULL COMMENT '캐리아이디', -- 캐리아이디
	`CRPW`      VARCHAR(30)  NOT NULL COMMENT '비밀번호', -- 비밀번호
	`CRNAME`    VARCHAR(50)  NOT NULL COMMENT '캐리실명', -- 캐리실명
	`CRNICK`    VARCHAR(50)  NOT NULL COMMENT '캐리닉네임', -- 캐리닉네임
	`CRPHONE`   VARCHAR(30)  NOT NULL COMMENT '핸드폰번호', -- 핸드폰번호
	`CRBIRTH`   INTEGER      NOT NULL COMMENT '생년월일', -- 생년월일
	`CRGENDER`  VARCHAR(5)   NOT NULL COMMENT '성별', -- 성별
	`CREMAIL`   VARCHAR(40)  NOT NULL COMMENT '이메일', -- 이메일
	`CRPHOTO`   MEDIUMBLOB   NULL     COMMENT '프로필사진', -- 프로필사진
	`CRINTRO`   MEDIUMTEXT   NULL     COMMENT '소갯말', -- 소갯말
	`CRBFPHOTO` MEDIUMBLOB   NULL     COMMENT '캐리바디프로필', -- 캐리바디프로필
	`CRDEPART`  MEDIUMTEXT   NULL     COMMENT '전문분야', -- 전문분야
	`CRFIELD`   MEDIUMTEXT   NULL     COMMENT '종목', -- 종목
	`CRCERTI1`  MEDIUMTEXT   NULL     COMMENT '자격및경력1', -- 자격및경력1
	`CRCERTI2`  MEDIUMTEXT   NULL     COMMENT '자격및경력2', -- 자격및경력2
	`CRCERTI3`  MEDIUMTEXT   NULL     COMMENT '자격및경력3', -- 자격및경력3
	`CRCERTI4`  MEDIUMTEXT   NULL     COMMENT '자격및경력4', -- 자격및경력4
	`CRCERTI5`  MEDIUMTEXT   NULL     COMMENT '자격및경력5', -- 자격및경력5
	`PLACENAME` VARCHAR(255) NULL     COMMENT '소속플레이스', -- 소속플레이스
	`PLACEIDX`  INTEGER      NULL     COMMENT '플레이스IDX' -- 플레이스IDX
)
COMMENT '캐리정보';

-- 캐리정보
ALTER TABLE `CARRY`
	ADD CONSTRAINT `PK_CARRY` -- 캐리정보 기본키
		PRIMARY KEY (
			`CRIDX` -- 캐리IDX
		);

ALTER TABLE `CARRY`
	MODIFY COLUMN `CRIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '캐리IDX';

ALTER TABLE `CARRY`
	AUTO_INCREMENT = 1;

-- 플레이스
CREATE TABLE `PLACE` (
	`PLACEIDX`     INTEGER     NOT NULL COMMENT '플레이스IDX', -- 플레이스IDX
	`PLACENAME`    VARCHAR(50) NOT NULL COMMENT '플레이스이름', -- 플레이스이름
	`OPENHOUR`     MEDIUMTEXT  NOT NULL COMMENT '운영시간', -- 운영시간
	`PARKING`      MEDIUMTEXT  NOT NULL COMMENT '주차시설', -- 주차시설
	`PLACEADDRESS` MEDIUMTEXT  NOT NULL COMMENT '플레이스주소', -- 플레이스주소
	`PLACEPHONE`   MEDIUMTEXT  NOT NULL COMMENT '플레이스번호' -- 플레이스번호
)
COMMENT '플레이스';

-- 플레이스
ALTER TABLE `PLACE`
	ADD CONSTRAINT `PK_PLACE` -- 플레이스 기본키
		PRIMARY KEY (
			`PLACEIDX` -- 플레이스IDX
		);

ALTER TABLE `PLACE`
	MODIFY COLUMN `PLACEIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '플레이스IDX';

ALTER TABLE `PLACE`
	AUTO_INCREMENT = 1;

-- 캐리상세페이지 리뷰댓글
CREATE TABLE `CARRYREVIEW` (
	`REVIEWIDX`     INTEGER    NOT NULL COMMENT '리뷰IDX', -- 리뷰IDX
	`REVIEWCONTENT` MEDIUMTEXT NULL     COMMENT '리뷰내용', -- 리뷰내용
	`CRIDX`         INTEGER    NULL     COMMENT '캐리IDX', -- 캐리IDX
	`MEMIDX`        INTEGER    NULL     COMMENT '회원번호' -- 회원번호
)
COMMENT '캐리상세페이지 리뷰댓글';

-- 캐리상세페이지 리뷰댓글
ALTER TABLE `CARRYREVIEW`
	ADD CONSTRAINT `PK_CARRYREVIEW` -- 캐리상세페이지 리뷰댓글 기본키
		PRIMARY KEY (
			`REVIEWIDX` -- 리뷰IDX
		);

ALTER TABLE `CARRYREVIEW`
	MODIFY COLUMN `REVIEWIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '리뷰IDX';

ALTER TABLE `CARRYREVIEW`
	AUTO_INCREMENT = 1;

-- 공지사항
CREATE TABLE `공지사항` (
)
COMMENT '공지사항';

-- 채팅방리스트
CREATE TABLE `CHATLIST` (
	`CHATIDX` INTEGER NOT NULL COMMENT '채팅방번호' -- 채팅방번호
)
COMMENT '채팅방리스트';

-- 채팅방리스트
ALTER TABLE `CHATLIST`
	ADD CONSTRAINT `PK_CHATLIST` -- 채팅방리스트 기본키
		PRIMARY KEY (
			`CHATIDX` -- 채팅방번호
		);

-- 수업정보
CREATE TABLE `PROGRAMINFO` (
	`PROIDX`     INTEGER NOT NULL COMMENT '수업IDX', -- 수업IDX
	`CRIDX`      INTEGER NOT NULL COMMENT '캐리IDX', -- 캐리IDX
	`PROPRICE1`  INTEGER NOT NULL COMMENT '수업1회가격', -- 수업1회가격
	`PROPRICE5`  INTEGER NOT NULL COMMENT '수업5회가격', -- 수업5회가격
	`PROPRICE10` INTEGER NOT NULL COMMENT '수업10회가격', -- 수업10회가격
	`PROPRICE20` INTEGER NOT NULL COMMENT '수업20회가격', -- 수업20회가격
	`FACEORNOT`  BOOLEAN NOT NULL COMMENT '비대면&대면' -- 비대면&대면
)
COMMENT '수업정보';

-- 수업정보
ALTER TABLE `PROGRAMINFO`
	ADD CONSTRAINT `PK_PROGRAMINFO` -- 수업정보 기본키
		PRIMARY KEY (
			`PROIDX` -- 수업IDX
		);

ALTER TABLE `PROGRAMINFO`
	MODIFY COLUMN `PROIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '수업IDX';

ALTER TABLE `PROGRAMINFO`
	AUTO_INCREMENT = 1;

-- 찜한리스트
CREATE TABLE `LIKELIST` (
	`LIKEIDX`   INTEGER NOT NULL COMMENT '좋아요IDX', -- 좋아요IDX
	`MEMIDX`    INTEGER NULL     COMMENT '회원번호', -- 회원번호
	`CRIDX`     INTEGER NULL     COMMENT '캐리IDX', -- 캐리IDX
	`LIKECHECK` BOOLEAN NULL     COMMENT '좋아요체크' -- 좋아요체크
)
COMMENT '찜한리스트';

-- 찜한리스트
ALTER TABLE `LIKELIST`
	ADD CONSTRAINT `PK_LIKELIST` -- 찜한리스트 기본키
		PRIMARY KEY (
			`LIKEIDX` -- 좋아요IDX
		);

ALTER TABLE `LIKELIST`
	MODIFY COLUMN `LIKEIDX` INTEGER NOT NULL AUTO_INCREMENT COMMENT '좋아요IDX';

ALTER TABLE `LIKELIST`
	AUTO_INCREMENT = 1;

-- 게시판
ALTER TABLE `BOARD`
	ADD CONSTRAINT `FK_MEMBER_TO_BOARD` -- 회원 -> 게시판
		FOREIGN KEY (
			`MEMIDX` -- 회원번호
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMIDX` -- 회원번호
		);

-- 채팅방내용
ALTER TABLE `CHATROOM`
	ADD CONSTRAINT `FK_CARRY_TO_CHATROOM` -- 캐리정보 -> 채팅방내용
		FOREIGN KEY (
			`CRIDX` -- 캐리번호
		)
		REFERENCES `CARRY` ( -- 캐리정보
			`CRIDX` -- 캐리IDX
		);

-- 채팅방내용
ALTER TABLE `CHATROOM`
	ADD CONSTRAINT `FK_MEMBER_TO_CHATROOM` -- 회원 -> 채팅방내용
		FOREIGN KEY (
			`MEMIDX` -- 회원번호
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMIDX` -- 회원번호
		);

-- 채팅방내용
ALTER TABLE `CHATROOM`
	ADD CONSTRAINT `FK_CHATLIST_TO_CHATROOM` -- 채팅방리스트 -> 채팅방내용
		FOREIGN KEY (
			`CHATIDX` -- 채팅방번호
		)
		REFERENCES `CHATLIST` ( -- 채팅방리스트
			`CHATIDX` -- 채팅방번호
		);

-- 회원바디기록
ALTER TABLE `MEMBERBODYINFO`
	ADD CONSTRAINT `FK_MEMBER_TO_MEMBERBODYINFO` -- 회원 -> 회원바디기록
		FOREIGN KEY (
			`MEMIDX` -- 회원번호
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMIDX` -- 회원번호
		);

-- 게시판댓글
ALTER TABLE `BOARDCOMMENT`
	ADD CONSTRAINT `FK_BOARD_TO_BOARDCOMMENT` -- 게시판 -> 게시판댓글
		FOREIGN KEY (
			`POSTIDX` -- 게시글IDX
		)
		REFERENCES `BOARD` ( -- 게시판
			`POSTIDX` -- 게시글IDX
		);

-- 결제
ALTER TABLE `PAYMENT`
	ADD CONSTRAINT `FK_MEMBER_TO_PAYMENT` -- 회원 -> 결제
		FOREIGN KEY (
			`MEMIDX` -- 회원번호
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMIDX` -- 회원번호
		);

-- 결제
ALTER TABLE `PAYMENT`
	ADD CONSTRAINT `FK_PROGRAMINFO_TO_PAYMENT` -- 수업정보 -> 결제
		FOREIGN KEY (
			`PROIDX` -- 수업IDX
		)
		REFERENCES `PROGRAMINFO` ( -- 수업정보
			`PROIDX` -- 수업IDX
		);

-- 캐리정보
ALTER TABLE `CARRY`
	ADD CONSTRAINT `FK_PLACE_TO_CARRY` -- 플레이스 -> 캐리정보
		FOREIGN KEY (
			`PLACEIDX` -- 플레이스IDX
		)
		REFERENCES `PLACE` ( -- 플레이스
			`PLACEIDX` -- 플레이스IDX
		);

-- 캐리상세페이지 리뷰댓글
ALTER TABLE `CARRYREVIEW`
	ADD CONSTRAINT `FK_CARRY_TO_CARRYREVIEW` -- 캐리정보 -> 캐리상세페이지 리뷰댓글
		FOREIGN KEY (
			`CRIDX` -- 캐리IDX
		)
		REFERENCES `CARRY` ( -- 캐리정보
			`CRIDX` -- 캐리IDX
		);

-- 캐리상세페이지 리뷰댓글
ALTER TABLE `CARRYREVIEW`
	ADD CONSTRAINT `FK_MEMBER_TO_CARRYREVIEW` -- 회원 -> 캐리상세페이지 리뷰댓글
		FOREIGN KEY (
			`MEMIDX` -- 회원번호
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMIDX` -- 회원번호
		);

-- 수업정보
ALTER TABLE `PROGRAMINFO`
	ADD CONSTRAINT `FK_CARRY_TO_PROGRAMINFO` -- 캐리정보 -> 수업정보
		FOREIGN KEY (
			`CRIDX` -- 캐리IDX
		)
		REFERENCES `CARRY` ( -- 캐리정보
			`CRIDX` -- 캐리IDX
		);

-- 찜한리스트
ALTER TABLE `LIKELIST`
	ADD CONSTRAINT `FK_MEMBER_TO_LIKELIST` -- 회원 -> 찜한리스트
		FOREIGN KEY (
			`MEMIDX` -- 회원번호
		)
		REFERENCES `MEMBER` ( -- 회원
			`MEMIDX` -- 회원번호
		);

-- 찜한리스트
ALTER TABLE `LIKELIST`
	ADD CONSTRAINT `FK_CARRY_TO_LIKELIST` -- 캐리정보 -> 찜한리스트
		FOREIGN KEY (
			`CRIDX` -- 캐리IDX
		)
		REFERENCES `CARRY` ( -- 캐리정보
			`CRIDX` -- 캐리IDX
		);