// SQL 정리
--------------------------------------------- 드랍

DROP TABLE MONEY;

DROP TABLE buyinfo;
DROP SEQUENCE BINFO_BCODE_SEQ;

DROP TABLE PRODUCTINFO;
DROP SEQUENCE PINFO_ICODE_SEQ;

---------------------------------------------
CREATE TABLE MONEY (
 MKEY INTEGER PRIMARY KEY,
 MNAME VARCHAR2(20) NOT NULL,
 MVALUE INTEGER NOT NULL,
 MCOUNT INTEGER NOT NULL
);

INSERT INTO MONEY VALUES (1,'오백원',500,10);
INSERT INTO MONEY VALUES (2,'백원',100,10);

SELECT * FROM MONEY;


commit;

-----------------------------------------------

CREATE TABLE BUYINFO (
    BUYCODE NUMBER(4) CONSTRAINT BINFO_BCODE_PK PRIMARY KEY,
    BUYQTY INTEGER CONSTRAINT BINFO_BQTY_NN NOT NULL,
    TOTALPRICE INTEGER CONSTRAINT BINFO_TPRICE_NN NOT NULL,
    ITEMCODE NUMBER --참조코드
);

CREATE SEQUENCE BINFO_BCODE_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL,20,14000,1);
INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL,5,3000,2);
INSERT INTO BUYINFO VALUES (BINFO_BCODE_SEQ.NEXTVAL,2,12000,4);

SELECT * FROM buyinfo;

commit;

--------------------------------------------------


CREATE TABLE PRODUCTINFO (
    ITEMCODE NUMBER(4) CONSTRAINT PINFO_ICODE_PF PRIMARY KEY,
    NAME VARCHAR2(20) CONSTRAINT PINFO_NAME_NN NOT NULL,
    PRICE INTEGER CONSTRAINT PINFO_PRICE_NN NOT NULL,
    ITEMQTY INTEGER
);

CREATE SEQUENCE PINFO_ICODE_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO PRODUCTINFO VALUES (PINFO_ICODE_SEQ.NEXTVAL, '콜라', 700, 10);
INSERT INTO PRODUCTINFO VALUES (PINFO_ICODE_SEQ.NEXTVAL, '사이다', 800, 10);
INSERT INTO PRODUCTINFO VALUES (PINFO_ICODE_SEQ.NEXTVAL, '마운틴듀', 600, 10);

SELECT * FROM PRODUCTINFO;

commit;